apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-nadinedb
    app.kubernetes.io/version: "12.4"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nadine
  name: db
spec:
  serviceName: db
  replicas: 1
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_PASSWORD
          value: somepassword
        image: gbottaro/nadine-postgresql:1.0.1
        name: db
        ports:
        - containerPort: 5432
      restartPolicy: Always
