apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: django-nadine
    app.kubernetes.io/version: "3.0.2"
    app.kubernetes.io/component: webframework
    app.kubernetes.io/part-of: nadine
  name: django
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: somepassword
        image: gbottaro/nadine-django:1.0.3
        name: django
        ports:
        - containerPort: 8000
      restartPolicy: Always
